'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class C2in1Laptops
    Public Property C2in1ID As Integer
    Public Property Touchscreen As String
    Public Property NumberOfScreens As Integer

    Public Overridable Property Laptop As Laptop

End Class
