'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ElectronicProduct
    Public Property ProductID As Integer
    Public Property Name As String
    Public Property Price As Integer
    Public Property Rating As Nullable(Of Double)
    Public Property Quantity As Integer
    Public Property Colour As String

    Public Overridable Property KitchenAppliance As KitchenAppliance
    Public Overridable Property Laptop As Laptop
    Public Overridable Property Phone As Phone

End Class
