'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GamingLaptop
    Public Property GamingLaptopID As Integer
    Public Property RefreshRate_Hz As Integer
    Public Property ResponseTime_ms As Integer

    Public Overridable Property Laptop As Laptop

End Class
