'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KitchenAppliance
    Public Property ApplianceID As Integer
    Public Property AnnualEnergyConsumption_kWh As Integer
    Public Property EuEnergyLabel As String
    Public Property SoundLevels As String

    Public Overridable Property Dishwasher As Dishwasher
    Public Overridable Property ElectronicProduct As ElectronicProduct
    Public Overridable Property Refrigerator As Refrigerator
    Public Overridable Property WashingMachine As WashingMachine

End Class
