'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Laptop
    Public Property LaptopID As Integer
    Public Property Brand As String
    Public Property RAM As String
    Public Property CPU As Integer
    Public Property GPU As Integer
    Public Property Battery As Double
    Public Property Display As String
    Public Property Storage_GB As Nullable(Of Integer)
    Public Property DisplaySize_inches As String

    Public Overridable Property C2in1Laptops As C2in1Laptops
    Public Overridable Property ElectronicProduct As ElectronicProduct
    Public Overridable Property GamingLaptop As GamingLaptop
    Public Overridable Property LaptopCPU As LaptopCPU
    Public Overridable Property LaptopGPU As LaptopGPU

End Class
