'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SQLServerDBEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SQLServerDBEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C2in1Laptops() As DbSet(Of C2in1Laptops)
    Public Overridable Property Dishwashers() As DbSet(Of Dishwasher)
    Public Overridable Property ElectronicProducts() As DbSet(Of ElectronicProduct)
    Public Overridable Property GamingLaptops() As DbSet(Of GamingLaptop)
    Public Overridable Property KitchenAppliances() As DbSet(Of KitchenAppliance)
    Public Overridable Property LaptopCPUs() As DbSet(Of LaptopCPU)
    Public Overridable Property LaptopGPUs() As DbSet(Of LaptopGPU)
    Public Overridable Property Laptops() As DbSet(Of Laptop)
    Public Overridable Property Phones() As DbSet(Of Phone)
    Public Overridable Property Refrigerators() As DbSet(Of Refrigerator)
    Public Overridable Property WashingMachines() As DbSet(Of WashingMachine)

End Class
