'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Dishwasher
    Public Property DishwasherID As Integer
    Public Property NoOfPrograms As Integer
    Public Property StepsOfTemperature As Integer
    Public Property LoadingCapacity As String

    Public Overridable Property KitchenAppliance As KitchenAppliance

End Class
