'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LaptopCPU
    Public Property LaptopCPUID As Integer
    Public Property Brand As String
    Public Property NumberOfCores As Integer
    Public Property Frequency_mHz As Integer

    Public Overridable Property Laptops As ICollection(Of Laptop) = New HashSet(Of Laptop)

End Class
