'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Phone
    Public Property PhoneID As Integer
    Public Property PhoneCPU As String
    Public Property Battery_mAh As Double
    Public Property Display As String
    Public Property Storage_GB As Integer
    Public Property Size_inches As Double

    Public Overridable Property ElectronicProduct As ElectronicProduct

End Class
