'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Refrigerator
    Public Property RefrigeratorID As Integer
    Public Property Volume As String
    Public Property SpecialCompartiments As String
    Public Property NoOfShelves As Integer

    Public Overridable Property KitchenAppliance As KitchenAppliance

End Class
